on:
  workflow_dispatch:
  schedule:
    - cron: '0 7/4 * * *'
      timezone: 'Asia/Tehran'

concurrency:
  group: secret
  cancel-in-progress: true

jobs:
  runsecret:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - run: |
          python -m pip install --upgrade pip
          pip install cryptography requests

      - env:
          CONFIG_TOML: ${{ secrets.CONFIG_TOML }}
          SECRET_PY: ${{ secrets.SECRET_PY }}
        run: |
          echo "$CONFIG_TOML" > config.toml
          echo "$SECRET_PY" > secret.py

      - run: |
          while true; do
            echo "ache"
            sleep 300
          done &

          python secret.py > /dev/null 2>&1
